# Generated by Django 4.1.2 on 2022-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='height',
            new_name='height_in',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='weight',
            new_name='weight_lbs',
        ),
        migrations.AlterField(
            model_name='condition',
            name='protein_recommendation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='sodium_recommendation',
            field=models.FloatField(),
        ),
    ]
