# Generated by Django 4.1.2 on 2022-11-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_phosphorus_recommendation_mg_max_condition_dv_k_recommendation_mg_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='serum_na_mEq_per_L_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
