# Generated by Django 4.1.2 on 2022-11-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_condition_serum_na_meq_per_l_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='serum_albuminmg_per_dL_max',
            new_name='serum_albumin_mg_per_dL_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_albuminmg_per_dL_min',
        ),
    ]
