# Generated by Django 4.1.2 on 2022-11-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_serum_albuminmg_per_dl_max_condition_serum_albumin_mg_per_dl_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='serum_albumin_mg_per_dL_min',
            new_name='serum_albumin_mg_per_dL',
        ),
    ]
