# Generated by Django 4.1.2 on 2022-11-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_gender_person_dv_k_mg_person_dv_phos_mg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gender'),
            preserve_default=False,
        ),
    ]
