# Generated by Django 4.1.2 on 2022-11-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='food_name',
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.person'),
            preserve_default=False,
        ),
    ]
