# Generated by Django 4.1.2 on 2022-11-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_foodconsumption_food_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodConsumption',
        ),
    ]
