# Generated by Django 4.1.2 on 2022-11-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_food_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodconsumption',
            old_name='food',
            new_name='food_name',
        ),
    ]
