# Generated by Django 4.1.2 on 2022-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_food_foodconsumption_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='person',
        ),
    ]
