# Generated by Django 4.1.2 on 2022-11-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_food_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='dv_k_recommendation_mg_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_k_recommendation_mg_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_phos_recommendation_mg_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_phos_recommendation_mg_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_protein_recommendation_g_per_kg_body_weight',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_sodium_recommendation_mg_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_sodium_recommendation_mg_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_water_recommendation_L_max_men',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_water_recommendation_L_max_women',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_water_recommendation_L_min_men',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='dv_water_recommendation_L_min_women',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_albumin_mg_per_dL',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_blood_sugar_mg_per_dL_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_blood_sugar_mg_per_dL_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_creatinine_mg_per_dL_men',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_creatinine_mg_per_dL_women',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_k_mg_per_dL_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_k_mg_per_dL_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_na_mEq_per_L_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_na_mEq_per_L_min',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_phos_mg_per_dL_max',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='serum_phos_mg_per_dL_min',
        ),
        migrations.RemoveField(
            model_name='food',
            name='dv_water_L',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dv_k_mg',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dv_phos_mg',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dv_protein_g_per_kg_body_weight',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dv_sodium_mg',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dv_water_L',
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_water_L', models.FloatField()),
                ('date_consumed', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person')),
            ],
        ),
    ]
