# Generated by Django 4.1.2 on 2022-11-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_condition_dv_k_recommendation_mg_max_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Water',
            new_name='WaterConsumption',
        ),
    ]
