# Generated by Django 4.1.2 on 2022-11-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='condition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.condition'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
