# Generated by Django 4.1.2 on 2022-11-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_person_condition_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.condition'),
        ),
    ]
