# Generated by Django 4.1.2 on 2022-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_person_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='person',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height_in',
        ),
        migrations.RemoveField(
            model_name='person',
            name='highbloodpressure',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_albumin_mg_per_dL',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_blood_sugar_mg_per_dL',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_creatinine_mg_per_dL',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_k_mg_per_dL',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_na_mEq_per_L_min',
        ),
        migrations.RemoveField(
            model_name='person',
            name='serum_phos_mg_per_dL_min',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight_lbs',
        ),
    ]
