# Generated by Django 4.1.2 on 2022-11-29 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0025_remove_person_condition_remove_person_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='condition',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dashboard.condition'),
        ),
        migrations.AddField(
            model_name='person',
            name='diabetes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height_in',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='highbloodpressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_lbs',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
