# Generated by Django 4.1.2 on 2022-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_person_condition_person_diabetes_person_height_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='condition',
        ),
        migrations.AlterField(
            model_name='person',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='highbloodpressure',
            field=models.BooleanField(default=False),
        ),
    ]
