# Generated by Django 4.1.2 on 2022-11-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_person_condition_alter_person_diabetes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
