# Generated by Django 4.1.2 on 2022-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_delete_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dv_protein_g_per_kg_body_weight',
            field=models.IntegerField(),
        ),
    ]
