# Generated by Django 4.1.2 on 2022-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_food_dv_protein_g_per_kg_body_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dv_k_mg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='dv_phos_mg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='dv_protein_g_per_kg_body_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='dv_sodium_mg',
            field=models.FloatField(),
        ),
    ]
