# Generated by Django 4.1.2 on 2022-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_food_dv_k_mg_alter_food_dv_phos_mg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='condition',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='serum_albumin_mg_per_dL',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='serum_blood_sugar_mg_per_dL',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='serum_creatinine_mg_per_dL',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='serum_k_mg_per_dL',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='serum_na_mEq_per_L_min',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='person',
            name='serum_phos_mg_per_dL_min',
            field=models.FloatField(default='0'),
        ),
    ]
