# Generated by Django 4.1.2 on 2022-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_person_condition_person_serum_albumin_mg_per_dl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='serum_blood_sugar_mg_per_dL',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='serum_creatinine_mg_per_dL',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='serum_na_mEq_per_L_min',
            field=models.FloatField(default='0'),
        ),
    ]
