# Generated by Django 4.1.2 on 2022-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_person_serum_blood_sugar_mg_per_dl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='condition',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
